# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

TEST_NODE_HOSTNAME = "vimana.avancecli"
TEST_NODE_NAME     = "VimanaAvanceCLI"
TEST_IP            = "33.33.40.15"



Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define 'test' do |test|
    
    test.vm.hostname = TEST_NODE_HOSTNAME
#     test.vm.box      = "opscode-ubuntu-14.04"
    test.vm.box      = "precise64"

    test.vm.network  "private_network", ip: TEST_IP

    test.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '3072']
      vb.customize ['modifyvm', :id, '--name',   TEST_NODE_NAME ]
    end
  end
end
